'use client';

import { useEffect, useState, useCallback, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { billingApi, levelsApi, schoolEventsApi, broadcastsApi } from '@/lib/api';
import { eventDisplayStatus } from '@/lib/event-status';
import { useStoredUser } from '@/lib/auth';
import {
  ChevronLeft, ChevronRight, Settings, Zap, Bus, CheckCircle2,
  Clock, AlertCircle, Euro, Plus, Pencil, Trash2, X, Check,
  CalendarDays, Filter, BellRing, ExternalLink, ChevronDown, ChevronUp, Users,
} from 'lucide-react';

const MONTHS_GR = [
  '', 'Ιανουάριος', 'Φεβρουάριος', 'Μάρτιος', 'Απρίλιος', 'Μάιος', 'Ιούνιος',
  'Ιούλιος', 'Αύγουστος', 'Σεπτέμβριος', 'Οκτώβριος', 'Νοέμβριος', 'Δεκέμβριος',
];

const EVENT_ENROLLMENT_STATUS: Record<string, { label: string; color: string }> = {
  pending_consent:  { label: 'Αναμ. Συναίνεση', color: 'bg-yellow-100 text-yellow-800' },
  consent_given:    { label: 'Συναίνεση',       color: 'bg-blue-100 text-blue-700' },
  consent_declined: { label: 'Απόρριψη',        color: 'bg-red-100 text-red-700' },
  pending_payment:  { label: 'Αναμ. Πληρωμή',  color: 'bg-orange-100 text-orange-700' },
  paid:             { label: 'Πληρωμένο',       color: 'bg-green-100 text-green-700' },
};

const SUBSIDY_TYPES: Record<string, string> = {
  bank: 'Τράπεζα',
  voucher: 'Voucher/Επίδομα',
  other: 'Άλλο',
};

const STATUS_STYLES: Record<string, { label: string; color: string; icon: any }> = {
  paid: { label: 'Πληρωμένο', color: 'bg-green-50 text-green-700 border-green-100', icon: CheckCircle2 },
  partial: { label: 'Μερική', color: 'bg-blue-50 text-blue-700 border-blue-100', icon: AlertCircle },
  unpaid: { label: 'Εκκρεμεί', color: 'bg-amber-50 text-amber-700 border-amber-100', icon: Clock },
};

function fmt(n: number) {
  return `€${n.toFixed(2)}`;
}

export default function BillingPage() {
  const user = useStoredUser();
  const schoolId = user?.schoolId ?? '';
  const router = useRouter();

  const now = new Date();
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [year, setYear] = useState(now.getFullYear());

  const [charges, setCharges] = useState<any[]>([]);
  const [stats, setStats] = useState<any>(null);
  const [levels, setLevels] = useState<any[]>([]);
  const [levelFees, setLevelFees] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [tab, setTab] = useState<'charges' | 'events' | 'settings'>('charges');
  const [showUnpaidOnly, setShowUnpaidOnly] = useState(false);

  // Events tab state
  const [events, setEvents] = useState<any[]>([]);
  const [eventsLoading, setEventsLoading] = useState(false);
  const [expandedEventId, setExpandedEventId] = useState<string | null>(null);
  const [eventEnrollments, setEventEnrollments] = useState<Record<string, any[]>>({});
  const [loadingEnrollments, setLoadingEnrollments] = useState<string | null>(null);
  const [markingPayment, setMarkingPayment] = useState<string | null>(null);
  const [sendingNotif, setSendingNotif] = useState<string | null>(null);

  // Settings modals
  const [editingLevelFee, setEditingLevelFee] = useState<any>(null); // { levelId, levelName, monthlyFee }
  const [editingOverride, setEditingOverride] = useState<any>(null); // student charge selected for override/subsidy management
  const [overrideData, setOverrideData] = useState<any>(null);
  const [subsidies, setSubsidies] = useState<any[]>([]);
  const [subsidyForm, setSubsidyForm] = useState<any>(null);

  // Pay modal
  const [payingCharge, setPayingCharge] = useState<any>(null);
  const [payAmount, setPayAmount] = useState('');
  const [payNotes, setPayNotes] = useState('');
  const [saving, setSaving] = useState(false);

  const autoGeneratedRef = useRef<string>('');

  const load = useCallback(async () => {
    if (!schoolId) return;
    setLoading(true);
    try {
      const [ch, st, lv, lf] = await Promise.all([
        billingApi.getCharges(schoolId, month, year),
        billingApi.stats(schoolId),
        levelsApi.list(schoolId),
        billingApi.getLevelFees(schoolId),
      ]);
      const chargesArr = Array.isArray(ch) ? ch : [];
      setCharges(chargesArr);
      setStats(st);
      setLevels(Array.isArray(lv) ? lv : []);
      setLevelFees(Array.isArray(lf) ? lf : []);

      // Auto-generate for the current month if no charges exist yet
      const now = new Date();
      const key = `${month}-${year}`;
      if (
        chargesArr.length === 0 &&
        month === now.getMonth() + 1 &&
        year === now.getFullYear() &&
        autoGeneratedRef.current !== key
      ) {
        autoGeneratedRef.current = key;
        setGenerating(true);
        try {
          await billingApi.generateCharges(schoolId, month, year);
          const fresh: any = await billingApi.getCharges(schoolId, month, year);
          setCharges(Array.isArray(fresh) ? fresh : []);
          const freshStats: any = await billingApi.stats(schoolId);
          setStats(freshStats);
        } finally {
          setGenerating(false);
        }
      }
    } finally {
      setLoading(false);
    }
  }, [schoolId, month, year]);

  useEffect(() => { load(); }, [load]);

  useEffect(() => {
    if (tab !== 'events' || !schoolId) return;
    setEventsLoading(true);
    schoolEventsApi.list(schoolId).then((evts: any) => {
      setEvents(Array.isArray(evts) ? evts : []);
    }).catch(() => setEvents([])).finally(() => setEventsLoading(false));
  }, [tab, schoolId]);

  async function loadEventEnrollments(eventId: string) {
    setLoadingEnrollments(eventId);
    try {
      const enrs: any = await schoolEventsApi.getEnrollments(schoolId, eventId);
      setEventEnrollments(prev => ({ ...prev, [eventId]: Array.isArray(enrs) ? enrs : [] }));
    } finally {
      setLoadingEnrollments(null);
    }
  }

  async function handleToggleEvent(eventId: string) {
    if (expandedEventId === eventId) {
      setExpandedEventId(null);
      return;
    }
    setExpandedEventId(eventId);
    if (!eventEnrollments[eventId]) {
      await loadEventEnrollments(eventId);
    }
  }

  async function handleMarkEventPayment(eventId: string, enrollmentId: string, paid: boolean) {
    setMarkingPayment(enrollmentId);
    try {
      await schoolEventsApi.markPayment(schoolId, eventId, enrollmentId, paid);
      await loadEventEnrollments(eventId);
    } finally {
      setMarkingPayment(null);
    }
  }

  async function notifyUnpaidForEvent(eventId: string, eventTitle: string) {
    const enrs = eventEnrollments[eventId] ?? [];
    const unpaid = enrs.filter((e: any) => e.status === 'pending_payment' || e.status === 'pending_consent');
    if (unpaid.length === 0) return;
    setSendingNotif(eventId);
    try {
      for (const enr of unpaid) {
        await broadcastsApi.send(schoolId, {
          title: `Υπενθύμιση: ${eventTitle}`,
          body: `Υπάρχει εκκρεμής ενέργεια για την εκδήλωση "${eventTitle}". Παρακαλούμε ενημερώστε τη γραμματεία.`,
          targetType: 'student',
          targetStudentId: enr.studentId,
        });
      }
    } catch {
      // ignore
    } finally {
      setSendingNotif(null);
    }
  }

  async function notifyUnpaidForMonth() {
    const unpaid = charges.filter(c => c.status !== 'paid');
    if (unpaid.length === 0) return;
    setSendingNotif('monthly');
    try {
      for (const c of unpaid) {
        await broadcastsApi.send(schoolId, {
          title: `Υπενθύμιση Πληρωμής — ${MONTHS_GR[month]} ${year}`,
          body: `Υπάρχει εκκρεμής πληρωμή για τον μήνα ${MONTHS_GR[month]} ${year}. Παρακαλούμε ενημερώστε τη γραμματεία.`,
          targetType: 'student',
          targetStudentId: c.studentId ?? c.student?.id,
        });
      }
    } catch {
      // ignore
    } finally {
      setSendingNotif(null);
    }
  }

  function prevMonth() {
    if (month === 1) { setMonth(12); setYear(y => y - 1); }
    else setMonth(m => m - 1);
  }
  function nextMonth() {
    if (month === 12) { setMonth(1); setYear(y => y + 1); }
    else setMonth(m => m + 1);
  }

  async function generate() {
    setGenerating(true);
    try {
      await billingApi.generateCharges(schoolId, month, year);
      await load();
    } finally {
      setGenerating(false);
    }
  }

  async function submitPay() {
    if (!payingCharge) return;
    setSaving(true);
    try {
      const amount = parseFloat(payAmount);
      await billingApi.updateCharge(schoolId, payingCharge.id, {
        paidAmount: amount,
        notes: payNotes || undefined,
      });
      setPayingCharge(null);
      await load();
    } finally {
      setSaving(false);
    }
  }

  async function markUnpaid(charge: any) {
    await billingApi.updateCharge(schoolId, charge.id, { paidAmount: 0, status: 'unpaid' });
    await load();
  }

  async function deleteCharge(charge: any) {
    if (!confirm(`Διαγραφή χρέωσης για ${charge.student.fullName};`)) return;
    await billingApi.deleteCharge(schoolId, charge.id);
    setCharges(prev => prev.filter(c => c.id !== charge.id));
  }

  async function saveLevelFee() {
    if (!editingLevelFee) return;
    await billingApi.upsertLevelFee(schoolId, editingLevelFee.levelId, {
      monthlyFee: parseFloat(editingLevelFee.monthlyFee) || 0,
      annualFee: editingLevelFee.annualFee ? parseFloat(editingLevelFee.annualFee) : null,
    });
    setEditingLevelFee(null);
    const lf: any = await billingApi.getLevelFees(schoolId);
    setLevelFees(Array.isArray(lf) ? lf : []);
  }

  async function openStudentSettings(charge: any) {
    setEditingOverride(charge);
    const [ov, subs] = await Promise.all([
      billingApi.getStudentFee(schoolId, charge.student.id).catch(() => null),
      billingApi.getSubsidies(schoolId, charge.student.id),
    ]);
    setOverrideData(ov ?? { discountPct: '', fixedAmount: '', reason: '' });
    setSubsidies(Array.isArray(subs) ? subs : []);
    setSubsidyForm(null);
  }

  async function saveOverride() {
    const d: any = {};
    if (overrideData.fixedAmount !== '' && overrideData.fixedAmount !== null) {
      d.fixedAmount = parseFloat(overrideData.fixedAmount);
      d.discountPct = null;
    } else if (overrideData.discountPct !== '' && overrideData.discountPct !== null) {
      d.discountPct = parseFloat(overrideData.discountPct);
      d.fixedAmount = null;
    }
    if (overrideData.reason) d.reason = overrideData.reason;
    await billingApi.upsertStudentFee(schoolId, editingOverride.student.id, d);
    setOverrideData(null);
  }

  async function removeOverride() {
    await billingApi.deleteStudentFee(schoolId, editingOverride.student.id);
    setOverrideData({ discountPct: '', fixedAmount: '', reason: '' });
  }

  async function saveSubsidy() {
    if (!subsidyForm) return;
    if (subsidyForm.id) {
      await billingApi.updateSubsidy(schoolId, editingOverride.student.id, subsidyForm.id, subsidyForm);
    } else {
      await billingApi.createSubsidy(schoolId, editingOverride.student.id, subsidyForm);
    }
    const subs: any = await billingApi.getSubsidies(schoolId, editingOverride.student.id);
    setSubsidies(Array.isArray(subs) ? subs : []);
    setSubsidyForm(null);
  }

  async function deleteSubsidy(subsidyId: string) {
    await billingApi.deleteSubsidy(schoolId, editingOverride.student.id, subsidyId);
    const subs: any = await billingApi.getSubsidies(schoolId, editingOverride.student.id);
    setSubsidies(Array.isArray(subs) ? subs : []);
  }

  const totalDue = charges.reduce((s, c) => s + Number(c.totalDue), 0);
  const totalPaid = charges.reduce((s, c) => s + Number(c.paidAmount), 0);
  const totalPending = totalDue - totalPaid;
  const paidCount = charges.filter(c => c.status === 'paid').length;
  const unpaidCount = charges.filter(c => c.status === 'unpaid').length;
  const partialCount = charges.filter(c => c.status === 'partial').length;

  return (
    <div>
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Οικονομικά</h1>
          <p className="text-sm text-gray-500 mt-0.5">Σχολικό Έτος {stats?.schoolYear ?? '...'}</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setTab(tab === 'settings' ? 'charges' : 'settings')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
              tab === 'settings'
                ? 'bg-gray-800 text-white'
                : 'border border-gray-200 text-gray-600 hover:bg-gray-50'
            }`}
          >
            <Settings className="h-4 w-4" />
            Ρυθμίσεις
          </button>
        </div>
      </div>

      {/* View tabs */}
      {tab !== 'settings' && (
        <div className="flex gap-1 mb-5 bg-gray-100 rounded-xl p-1 w-fit">
          <button
            onClick={() => setTab('charges')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${tab === 'charges' ? 'bg-white shadow-sm text-gray-900' : 'text-gray-500 hover:text-gray-700'}`}
          >
            <Euro className="h-4 w-4" /> Μηνιαία
          </button>
          <button
            onClick={() => setTab('events')}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors ${tab === 'events' ? 'bg-white shadow-sm text-gray-900' : 'text-gray-500 hover:text-gray-700'}`}
          >
            <CalendarDays className="h-4 w-4" /> Εκδηλώσεις
          </button>
        </div>
      )}

      {tab === 'settings' ? (
        <SettingsTab
          levels={levels}
          levelFees={levelFees}
          editingLevelFee={editingLevelFee}
          setEditingLevelFee={setEditingLevelFee}
          saveLevelFee={saveLevelFee}
        />
      ) : tab === 'events' ? (
        /* ---- Events tab ---- */
        <div className="space-y-3">
          {eventsLoading ? (
            <div className="text-center py-16 text-gray-400">Φόρτωση...</div>
          ) : events.length === 0 ? (
            <div className="text-center py-16 text-gray-400">
              <CalendarDays className="h-10 w-10 mx-auto mb-3 text-gray-300" />
              <p className="font-medium text-gray-500">Δεν υπάρχουν εκδηλώσεις</p>
            </div>
          ) : events.map((evt: any) => {
            const enrs = eventEnrollments[evt.id] ?? [];
            const isExpanded = expandedEventId === evt.id;
            const pendingCount = enrs.filter((e: any) => e.status === 'pending_payment' || e.status === 'pending_consent').length;
            const paidCount = enrs.filter((e: any) => e.status === 'paid').length;
            const totalCount = enrs.length;

            return (
              <div key={evt.id} className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div
                  className="flex items-center gap-4 px-5 py-4 cursor-pointer hover:bg-gray-50/60 transition-colors"
                  onClick={() => handleToggleEvent(evt.id)}
                >
                  <div className="w-10 h-10 rounded-xl bg-violet-50 flex items-center justify-center shrink-0">
                    <CalendarDays className="w-5 h-5 text-violet-500" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-semibold text-gray-900">{evt.title}</span>
                      {eventDisplayStatus(evt.status, evt.eventDate) === 'published' && <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full">Δημοσιευμένο</span>}
                      {eventDisplayStatus(evt.status, evt.eventDate) === 'completed' && <span className="text-xs bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full">Ολοκληρώθηκε</span>}
                    </div>
                    <div className="flex items-center gap-3 mt-0.5 text-xs text-gray-500">
                      {evt.eventDate && <span>{new Date(evt.eventDate).toLocaleDateString('el-GR')}</span>}
                      {evt.costPerChild > 0 && <span className="font-medium text-gray-700">€{evt.costPerChild}/παιδί</span>}
                      {isExpanded && totalCount > 0 && (
                        <>
                          <span className="text-green-600 font-medium">{paidCount} πληρωμένοι</span>
                          {pendingCount > 0 && <span className="text-orange-600 font-medium">{pendingCount} εκκρεμούν</span>}
                        </>
                      )}
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    {isExpanded && pendingCount > 0 && (
                      <button
                        onClick={e => { e.stopPropagation(); notifyUnpaidForEvent(evt.id, evt.title); }}
                        disabled={sendingNotif === evt.id}
                        className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50"
                      >
                        <BellRing className="h-3.5 w-3.5" />
                        {sendingNotif === evt.id ? 'Αποστολή...' : `Ειδοποίηση (${pendingCount})`}
                      </button>
                    )}
                    {isExpanded ? <ChevronUp className="h-4 w-4 text-gray-400" /> : <ChevronDown className="h-4 w-4 text-gray-400" />}
                  </div>
                </div>

                {isExpanded && (
                  <div className="border-t border-gray-100">
                    {loadingEnrollments === evt.id ? (
                      <div className="py-6 text-center text-gray-400 text-sm">Φόρτωση...</div>
                    ) : enrs.length === 0 ? (
                      <div className="py-6 text-center text-gray-400 text-sm">Δεν υπάρχουν εγγεγραμμένοι μαθητές.</div>
                    ) : (
                      <div className="divide-y divide-gray-50">
                        {enrs.map((enr: any) => (
                          <div key={enr.id} className="flex items-center gap-4 px-5 py-3">
                            <div className="w-7 h-7 rounded-full bg-gray-100 flex items-center justify-center shrink-0">
                              {enr.student.avatarUrl ? (
                                <img src={enr.student.avatarUrl} className="w-7 h-7 rounded-full object-cover" />
                              ) : (
                                <span className="text-xs font-bold text-gray-400">{enr.student.fullName.charAt(0)}</span>
                              )}
                            </div>
                            <div className="flex-1 min-w-0">
                              <span className="font-medium text-gray-900 text-sm">{enr.student.fullName}</span>
                            </div>
                            <span className={`text-xs px-2.5 py-1 rounded-full font-medium shrink-0 ${EVENT_ENROLLMENT_STATUS[enr.status]?.color ?? 'bg-gray-100 text-gray-500'}`}>
                              {EVENT_ENROLLMENT_STATUS[enr.status]?.label ?? enr.status}
                            </span>
                            {enr.status === 'pending_payment' && (
                              <button
                                onClick={() => handleMarkEventPayment(evt.id, enr.id, true)}
                                disabled={markingPayment === enr.id}
                                className="flex items-center gap-1 px-2.5 py-1 text-xs bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 shrink-0"
                              >
                                <Check className="h-3 w-3" /> Εξόφληση
                              </button>
                            )}
                            {enr.status === 'paid' && (
                              <button
                                onClick={() => handleMarkEventPayment(evt.id, enr.id, false)}
                                disabled={markingPayment === enr.id}
                                className="px-2.5 py-1 text-xs text-gray-400 hover:text-red-500 border border-gray-200 rounded-lg shrink-0"
                              >
                                Αναίρεση
                              </button>
                            )}
                            <button
                              onClick={() => router.push(`/school/students/${enr.studentId}`)}
                              className="p-1.5 text-gray-300 hover:text-indigo-500 shrink-0"
                              title="Προφίλ μαθητή"
                            >
                              <ExternalLink className="h-3.5 w-3.5" />
                            </button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      ) : (
        <>
          {/* School-year summary dashboard */}
          {stats?.sy && (
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5 mb-5">
              <div className="flex items-center justify-between mb-4">
                <h2 className="font-bold text-gray-900">Σύνολο Σχολικού Έτους {stats.schoolYear}</h2>
                <span className="text-xs text-gray-400">Εως σήμερα</span>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
                <div className="bg-indigo-50 rounded-xl p-4">
                  <div className="text-xs text-indigo-600 mb-1 font-medium">Εισπράχθηκαν</div>
                  <div className="text-2xl font-bold text-indigo-700">{fmt(stats.sy.totalPaid)}</div>
                  <div className="text-xs text-indigo-400 mt-0.5">από {fmt(stats.sy.totalDue)} συνολικά</div>
                </div>
                <div className="bg-amber-50 rounded-xl p-4">
                  <div className="text-xs text-amber-600 mb-1 font-medium">Εκκρεμούν</div>
                  <div className="text-2xl font-bold text-amber-700">{fmt(Math.max(0, stats.sy.totalDue - stats.sy.totalPaid))}</div>
                  <div className="text-xs text-amber-400 mt-0.5">{stats.studentsOwingThisMonth} μαθητές αυτόν τον μήνα</div>
                </div>
                <div className="bg-gray-50 rounded-xl p-4">
                  <div className="text-xs text-gray-500 mb-2 font-medium">Ανάλυση χρεώσεων</div>
                  <div className="space-y-1">
                    {stats.sy.schoolFees > 0 && <div className="flex justify-between text-xs"><span className="text-gray-500">Δίδακτρα</span><span className="font-medium text-gray-700">{fmt(stats.sy.schoolFees)}</span></div>}
                    {stats.sy.busFees > 0 && <div className="flex justify-between text-xs"><span className="text-gray-500">Σχολικό</span><span className="font-medium text-gray-700">{fmt(stats.sy.busFees)}</span></div>}
                    {stats.sy.activityFees > 0 && <div className="flex justify-between text-xs"><span className="text-gray-500">Δραστηριότητες</span><span className="font-medium text-gray-700">{fmt(stats.sy.activityFees)}</span></div>}
                  </div>
                </div>
                <div className="bg-emerald-50 rounded-xl p-4">
                  <div className="text-xs text-emerald-600 mb-2 font-medium">Επιδοτήσεις / Voucher</div>
                  <div className="text-2xl font-bold text-emerald-700">{fmt(stats.sy.subsidies)}</div>
                  <div className="text-xs text-emerald-400 mt-0.5">αφαιρέθηκαν αυτόματα</div>
                </div>
              </div>
              {/* Progress bar */}
              {stats.sy.totalDue > 0 && (
                <div className="mt-1">
                  <div className="flex justify-between text-xs text-gray-400 mb-1">
                    <span>Εισπράχθηκε {Math.round((stats.sy.totalPaid / stats.sy.totalDue) * 100)}%</span>
                    <span>Εκκρεμεί {Math.round(((stats.sy.totalDue - stats.sy.totalPaid) / stats.sy.totalDue) * 100)}%</span>
                  </div>
                  <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-indigo-500 rounded-full transition-all"
                      style={{ width: `${Math.min(100, (stats.sy.totalPaid / stats.sy.totalDue) * 100)}%` }}
                    />
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Month selector + stats */}
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5 mb-5">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <button onClick={prevMonth} className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors">
                  <ChevronLeft className="h-4 w-4 text-gray-600" />
                </button>
                <span className="text-lg font-bold text-gray-900 min-w-[200px] text-center">
                  {MONTHS_GR[month]} {year}
                </span>
                <button onClick={nextMonth} className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors">
                  <ChevronRight className="h-4 w-4 text-gray-600" />
                </button>
              </div>
              <button
                onClick={generate}
                disabled={generating}
                className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700 disabled:opacity-50 transition-colors"
              >
                {generating ? (
                  <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                ) : (
                  <Zap className="h-4 w-4" />
                )}
                Δημιουργία Χρεώσεων
              </button>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              <div className="bg-gray-50 rounded-xl p-3">
                <div className="text-xs text-gray-500 mb-1">Χρεώσεις μήνα</div>
                <div className="text-xl font-bold text-gray-900">{fmt(totalDue)}</div>
              </div>
              <div className="bg-green-50 rounded-xl p-3">
                <div className="text-xs text-green-600 mb-1">Πληρωμένο</div>
                <div className="text-xl font-bold text-green-700">{fmt(totalPaid)}</div>
              </div>
              <div className="bg-amber-50 rounded-xl p-3">
                <div className="text-xs text-amber-600 mb-1">Εκκρεμεί</div>
                <div className="text-xl font-bold text-amber-700">{fmt(totalPending)}</div>
              </div>
              <div className="bg-gray-50 rounded-xl p-3">
                <div className="text-xs text-gray-500 mb-1">Μαθητές</div>
                <div className="flex items-center gap-1.5 text-sm mt-1">
                  <span className="text-green-700 font-bold">{paidCount}</span>
                  <span className="text-xs text-gray-400">εξοφλ.</span>
                  <span className="text-gray-300 mx-1">·</span>
                  <span className="text-amber-700 font-bold">{unpaidCount}</span>
                  <span className="text-xs text-gray-400">εκκρ.</span>
                  {partialCount > 0 && <><span className="text-gray-300 mx-1">·</span><span className="text-blue-700 font-bold">{partialCount}</span><span className="text-xs text-gray-400">μερ.</span></>}
                </div>
              </div>
            </div>
          </div>

          {/* Filter bar */}
          {!loading && charges.length > 0 && (
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setShowUnpaidOnly(!showUnpaidOnly)}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors border ${
                    showUnpaidOnly
                      ? 'bg-amber-50 border-amber-200 text-amber-700'
                      : 'border-gray-200 text-gray-500 hover:bg-gray-50'
                  }`}
                >
                  <Filter className="h-3.5 w-3.5" />
                  Μόνο Ανεξόφλητοι
                  {showUnpaidOnly && (
                    <span className="bg-amber-200 text-amber-800 text-xs px-1.5 py-0.5 rounded-full">
                      {charges.filter(c => c.status !== 'paid').length}
                    </span>
                  )}
                </button>
              </div>
              {charges.filter(c => c.status !== 'paid').length > 0 && (
                <button
                  onClick={notifyUnpaidForMonth}
                  disabled={sendingNotif === 'monthly'}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-sm border border-indigo-200 text-indigo-600 rounded-lg hover:bg-indigo-50 disabled:opacity-50"
                >
                  <BellRing className="h-3.5 w-3.5" />
                  {sendingNotif === 'monthly' ? 'Αποστολή...' : `Ειδοποίηση ανεξόφλητων (${charges.filter(c => c.status !== 'paid').length})`}
                </button>
              )}
            </div>
          )}

          {/* Charge list */}
          {loading ? (
            <div className="text-center py-16 text-gray-400">Φόρτωση...</div>
          ) : charges.length === 0 ? (
            <div className="text-center py-16 text-gray-400">
              <Euro className="h-10 w-10 mx-auto mb-3 text-gray-300" />
              <p className="font-medium text-gray-500">Δεν υπάρχουν χρεώσεις για αυτόν τον μήνα</p>
              <p className="text-sm mt-1">Πατήστε "Δημιουργία Χρεώσεων" για να δημιουργηθούν αυτόματα</p>
            </div>
          ) : (
            <div className="space-y-2">
              {charges.filter(c => !showUnpaidOnly || c.status !== 'paid').map((charge: any) => {
                const s = STATUS_STYLES[charge.status] ?? STATUS_STYLES.unpaid;
                const Icon = s.icon;
                const levelName = charge.student.enrollments?.[0]?.class?.level?.name ?? '—';
                return (
                  <div key={charge.id} className="bg-white rounded-xl border border-gray-100 shadow-sm p-4">
                    <div className="flex items-center gap-4">
                      {/* Student info */}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <button
                            onClick={() => router.push(`/school/students/${charge.studentId ?? charge.student?.id}`)}
                            className="font-semibold text-gray-900 truncate hover:text-indigo-600 transition-colors text-left"
                          >
                            {charge.student.fullName}
                          </button>
                          <span className="text-xs text-gray-400 bg-gray-50 px-2 py-0.5 rounded-full shrink-0">{levelName}</span>
                        </div>
                        <div className="flex items-center gap-3 mt-1 text-xs text-gray-500">
                          {Number(charge.schoolFee) > 0 && (
                            <span>Δίδακτρα: <span className="font-medium text-gray-700">{fmt(Number(charge.schoolFee))}</span></span>
                          )}
                          {Number(charge.busFee) > 0 && (
                            <span className="flex items-center gap-0.5">
                              <Bus className="h-3 w-3" /> {fmt(Number(charge.busFee))}
                            </span>
                          )}
                          {Number(charge.activityFees) > 0 && (
                            <span className="flex items-center gap-0.5">
                              <Zap className="h-3 w-3" /> {fmt(Number(charge.activityFees))}
                            </span>
                          )}
                          {Number(charge.subsidyTotal) > 0 && (
                            <span className="text-emerald-600">−{fmt(Number(charge.subsidyTotal))} επιδότηση</span>
                          )}
                        </div>
                      </div>

                      {/* Total */}
                      <div className="text-right shrink-0">
                        <div className="text-lg font-bold text-gray-900">{fmt(Number(charge.totalDue))}</div>
                        {charge.status === 'partial' && (
                          <div className="text-xs text-blue-600">Πληρωμένο: {fmt(Number(charge.paidAmount))}</div>
                        )}
                      </div>

                      {/* Status badge */}
                      <div className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border text-xs font-medium shrink-0 ${s.color}`}>
                        <Icon className="h-3.5 w-3.5" />
                        {s.label}
                      </div>

                      {/* Actions */}
                      <div className="flex items-center gap-1.5 shrink-0">
                        <button
                          onClick={() => openStudentSettings(charge)}
                          className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors"
                          title="Ρυθμίσεις μαθητή"
                        >
                          <Settings className="h-4 w-4" />
                        </button>
                        {charge.status === 'paid' ? (
                          <button
                            onClick={() => markUnpaid(charge)}
                            className="p-1.5 rounded-lg hover:bg-amber-50 text-gray-400 hover:text-amber-600 transition-colors"
                            title="Αναίρεση πληρωμής"
                          >
                            <X className="h-4 w-4" />
                          </button>
                        ) : (
                          <button
                            onClick={() => {
                              setPayingCharge(charge);
                              setPayAmount(charge.totalDue.toString());
                              setPayNotes('');
                            }}
                            className="flex items-center gap-1 px-3 py-1.5 bg-green-600 text-white rounded-lg text-xs font-medium hover:bg-green-700 transition-colors"
                          >
                            <Check className="h-3.5 w-3.5" />
                            Πληρωμή
                          </button>
                        )}
                        <button
                          onClick={() => deleteCharge(charge)}
                          className="p-1.5 rounded-lg hover:bg-red-50 text-gray-300 hover:text-red-500 transition-colors"
                          title="Διαγραφή χρέωσης"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </div>
                    {charge.notes && (
                      <div className="mt-2 text-xs text-gray-400 pl-0">{charge.notes}</div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </>
      )}

      {/* Pay modal */}
      {payingCharge && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6">
            <h3 className="text-lg font-bold text-gray-900 mb-1">Καταχώρηση Πληρωμής</h3>
            <p className="text-sm text-gray-500 mb-5">{payingCharge.student.fullName} — Σύνολο: {fmt(Number(payingCharge.totalDue))}</p>
            <label className="block text-sm font-medium text-gray-700 mb-1">Ποσό που καταβλήθηκε (€)</label>
            <input
              type="number"
              min="0"
              step="0.01"
              value={payAmount}
              onChange={e => setPayAmount(e.target.value)}
              className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300 mb-4"
            />
            <label className="block text-sm font-medium text-gray-700 mb-1">Σημειώσεις (προαιρετικό)</label>
            <input
              value={payNotes}
              onChange={e => setPayNotes(e.target.value)}
              placeholder="π.χ. Μετρητά, Μεταφορά..."
              className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300 mb-6"
            />
            <div className="flex gap-3">
              <button onClick={() => setPayingCharge(null)} className="flex-1 py-2.5 rounded-xl border border-gray-200 text-sm font-medium text-gray-600 hover:bg-gray-50">
                Ακύρωση
              </button>
              <button
                onClick={submitPay}
                disabled={saving || !payAmount}
                className="flex-1 py-2.5 rounded-xl bg-green-600 text-white text-sm font-medium hover:bg-green-700 disabled:opacity-50"
              >
                {saving ? 'Αποθήκευση...' : 'Αποθήκευση'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Student settings modal (override + subsidies) */}
      {editingOverride && (
        <StudentFeeModal
          charge={editingOverride}
          overrideData={overrideData}
          setOverrideData={setOverrideData}
          subsidies={subsidies}
          subsidyForm={subsidyForm}
          setSubsidyForm={setSubsidyForm}
          onClose={() => { setEditingOverride(null); load(); }}
          saveOverride={saveOverride}
          removeOverride={removeOverride}
          saveSubsidy={saveSubsidy}
          deleteSubsidy={deleteSubsidy}
        />
      )}
    </div>
  );
}

function SettingsTab({ levels, levelFees, editingLevelFee, setEditingLevelFee, saveLevelFee }: any) {
  const feeMap: Record<string, any> = {};
  levelFees.forEach((lf: any) => { feeMap[lf.levelId] = lf; });

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
      <h2 className="text-base font-bold text-gray-900 mb-1">Τιμολόγηση ανά Βαθμίδα</h2>
      <p className="text-sm text-gray-500 mb-5">Μηνιαία δίδακτρα + εφάπαξ εγγραφή για κάθε βαθμίδα</p>
      {levels.length === 0 && (
        <p className="text-sm text-gray-400">Δεν υπάρχουν βαθμίδες. Δημιουργήστε βαθμίδες στις ρυθμίσεις.</p>
      )}
      <div className="space-y-2">
        {levels.map((level: any) => {
          const fee = feeMap[level.id];
          const isEditing = editingLevelFee?.levelId === level.id;
          return (
            <div key={level.id} className="border border-gray-100 rounded-xl p-4">
              <div className="flex items-center gap-4">
                <div className="flex-1">
                  <div className="font-medium text-gray-900">{level.name}</div>
                  {fee && !isEditing && (
                    <div className="flex items-center gap-3 text-sm text-gray-500 mt-0.5">
                      <span>{fmt(Number(fee.monthlyFee))}/μήνα</span>
                      {fee.annualFee && <span className="text-purple-600">+ {fmt(Number(fee.annualFee))} εγγραφή/έτος</span>}
                    </div>
                  )}
                </div>
                {!isEditing && (
                  <button
                    onClick={() => setEditingLevelFee({
                      levelId: level.id,
                      levelName: level.name,
                      monthlyFee: fee ? Number(fee.monthlyFee).toFixed(2) : '',
                      annualFee: fee?.annualFee ? Number(fee.annualFee).toFixed(2) : '',
                    })}
                    className="flex items-center gap-1.5 px-3 py-1.5 border border-gray-200 rounded-lg text-sm text-gray-600 hover:bg-gray-50 transition-colors"
                  >
                    <Pencil className="h-3.5 w-3.5" />
                    {fee ? 'Αλλαγή' : 'Ορισμός'}
                  </button>
                )}
              </div>
              {isEditing && (
                <div className="mt-3 pt-3 border-t border-gray-100 space-y-3">
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-medium text-gray-600 mb-1">Μηνιαία δίδακτρα (€)</label>
                      <input
                        type="number"
                        min="0"
                        step="0.01"
                        value={editingLevelFee.monthlyFee}
                        onChange={e => setEditingLevelFee({ ...editingLevelFee, monthlyFee: e.target.value })}
                        placeholder="π.χ. 420"
                        className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
                        autoFocus
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-gray-600 mb-1">Εγγραφή αρχής έτους (€)</label>
                      <input
                        type="number"
                        min="0"
                        step="0.01"
                        value={editingLevelFee.annualFee}
                        onChange={e => setEditingLevelFee({ ...editingLevelFee, annualFee: e.target.value })}
                        placeholder="π.χ. 100 (γραφική ύλη)"
                        className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
                      />
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <button onClick={() => setEditingLevelFee(null)} className="flex-1 py-2 rounded-lg border border-gray-200 text-sm text-gray-600 hover:bg-gray-50">
                      Ακύρωση
                    </button>
                    <button onClick={saveLevelFee} className="flex-1 py-2 rounded-lg bg-indigo-600 text-white text-sm font-medium hover:bg-indigo-700">
                      Αποθήκευση
                    </button>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function StudentFeeModal({ charge, overrideData, setOverrideData, subsidies, subsidyForm, setSubsidyForm, onClose, saveOverride, removeOverride, saveSubsidy, deleteSubsidy }: any) {
  const [innerTab, setInnerTab] = useState<'override' | 'subsidies'>('override');

  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-lg max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between p-5 border-b border-gray-100">
          <div>
            <h3 className="font-bold text-gray-900">{charge.student.fullName}</h3>
            <p className="text-xs text-gray-500 mt-0.5">Ρυθμίσεις χρέωσης</p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="flex gap-1 p-4 pb-0">
          {(['override', 'subsidies'] as const).map(t => (
            <button
              key={t}
              onClick={() => setInnerTab(t)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                innerTab === t ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100'
              }`}
            >
              {t === 'override' ? 'Προσαρμογή Ποσού' : 'Επιδοτήσεις'}
            </button>
          ))}
        </div>

        <div className="flex-1 overflow-y-auto p-5">
          {innerTab === 'override' && overrideData !== null && (
            <div className="space-y-4">
              <p className="text-sm text-gray-500">Εφαρμόστε έκπτωση ή ορίστε σταθερό ποσό διδάκτρων για αυτόν τον μαθητή.</p>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Σταθερό Ποσό (€) <span className="text-gray-400 font-normal">— αντικαθιστά το ποσό βαθμίδας</span></label>
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  value={overrideData.fixedAmount ?? ''}
                  onChange={e => setOverrideData({ ...overrideData, fixedAmount: e.target.value, discountPct: '' })}
                  placeholder="π.χ. 250.00"
                  className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
                />
              </div>
              <div className="flex items-center gap-2 text-xs text-gray-400">
                <div className="h-px flex-1 bg-gray-100" /> ή <div className="h-px flex-1 bg-gray-100" />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Έκπτωση (%) <span className="text-gray-400 font-normal">— επί του ποσού βαθμίδας</span></label>
                <input
                  type="number"
                  min="0"
                  max="100"
                  step="0.1"
                  value={overrideData.discountPct ?? ''}
                  onChange={e => setOverrideData({ ...overrideData, discountPct: e.target.value, fixedAmount: '' })}
                  placeholder="π.χ. 10 (= 10%)"
                  className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Αιτιολογία</label>
                <input
                  value={overrideData.reason ?? ''}
                  onChange={e => setOverrideData({ ...overrideData, reason: e.target.value })}
                  placeholder="π.χ. Έκπτωση αδελφών, Υπάλληλος"
                  className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
                />
              </div>
              <div className="flex gap-2 pt-2">
                <button
                  onClick={removeOverride}
                  className="px-4 py-2 rounded-xl border border-red-200 text-red-600 text-sm font-medium hover:bg-red-50"
                >
                  Αφαίρεση
                </button>
                <button
                  onClick={saveOverride}
                  className="flex-1 py-2 rounded-xl bg-indigo-600 text-white text-sm font-medium hover:bg-indigo-700"
                >
                  Αποθήκευση
                </button>
              </div>
            </div>
          )}

          {innerTab === 'subsidies' && (
            <div className="space-y-3">
              <p className="text-sm text-gray-500">Επιδοτήσεις από τράπεζα, voucher ή άλλο φορέα (αφαιρούνται αυτόματα).</p>
              {subsidies.map((sub: any) => (
                <div key={sub.id} className="flex items-start gap-3 p-3 border border-gray-100 rounded-xl">
                  <div className="flex-1 min-w-0">
                    <div className="font-medium text-sm text-gray-900">{sub.name}</div>
                    <div className="text-xs text-gray-500">{SUBSIDY_TYPES[sub.subsidyType] ?? sub.subsidyType} · {fmt(Number(sub.monthlyAmount))}/μήνα</div>
                    {sub.notes && <div className="text-xs text-gray-400 mt-0.5">{sub.notes}</div>}
                  </div>
                  <div className="flex items-center gap-1 shrink-0">
                    <button onClick={() => setSubsidyForm(sub)} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400">
                      <Pencil className="h-3.5 w-3.5" />
                    </button>
                    <button onClick={() => deleteSubsidy(sub.id)} className="p-1.5 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-500">
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                  </div>
                </div>
              ))}

              {subsidyForm !== null ? (
                <div className="border border-indigo-100 rounded-xl p-4 space-y-3 bg-indigo-50/30">
                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">Όνομα φορέα</label>
                    <input
                      value={subsidyForm.name ?? ''}
                      onChange={e => setSubsidyForm({ ...subsidyForm, name: e.target.value })}
                      placeholder="π.χ. Alpha Bank, ΕΣΠΑ Voucher"
                      className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs font-medium text-gray-700 mb-1">Τύπος</label>
                      <select
                        value={subsidyForm.subsidyType ?? 'bank'}
                        onChange={e => setSubsidyForm({ ...subsidyForm, subsidyType: e.target.value })}
                        className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300 bg-white"
                      >
                        {Object.entries(SUBSIDY_TYPES).map(([k, v]) => (
                          <option key={k} value={k}>{v}</option>
                        ))}
                      </select>
                    </div>
                    <div>
                      <label className="block text-xs font-medium text-gray-700 mb-1">Ποσό/μήνα (€)</label>
                      <input
                        type="number"
                        min="0"
                        step="0.01"
                        value={subsidyForm.monthlyAmount ?? ''}
                        onChange={e => setSubsidyForm({ ...subsidyForm, monthlyAmount: e.target.value })}
                        placeholder="250.00"
                        className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">Σημειώσεις</label>
                    <input
                      value={subsidyForm.notes ?? ''}
                      onChange={e => setSubsidyForm({ ...subsidyForm, notes: e.target.value })}
                      placeholder="π.χ. Πληρώνει το 50% των διδάκτρων"
                      className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300"
                    />
                  </div>
                  <div className="flex gap-2">
                    <button onClick={() => setSubsidyForm(null)} className="flex-1 py-2 rounded-lg border border-gray-200 text-sm text-gray-600 hover:bg-gray-50">
                      Ακύρωση
                    </button>
                    <button onClick={saveSubsidy} className="flex-1 py-2 rounded-lg bg-indigo-600 text-white text-sm font-medium hover:bg-indigo-700">
                      Αποθήκευση
                    </button>
                  </div>
                </div>
              ) : (
                <button
                  onClick={() => setSubsidyForm({ name: '', subsidyType: 'bank', monthlyAmount: '', notes: '' })}
                  className="flex items-center gap-2 w-full p-3 border-2 border-dashed border-gray-200 rounded-xl text-sm text-gray-400 hover:border-indigo-200 hover:text-indigo-500 transition-colors"
                >
                  <Plus className="h-4 w-4" /> Προσθήκη Επιδότησης
                </button>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
